---

name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ant{,-optional} \
            ivy \
            junit \
            openjdk-17-{jdk-headless,doc} \
            python3-m2crypto \
            osc
      - name: Setup
        run: |
          git config tar.tar.xz.command 'xz -9'
      - name: Build
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        run: |
          ant -lib /usr/share/java/ivy.jar \
            -v -noinput build
# Test disabled because Ubintu 22.04 does not provide ant-junitlauncher.jar
#      - name: Test
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
#        run: |
#          ant -lib /usr/share/java/ivy.jar:/usr/share/java/junit-jupiter-api.jar \
#            -v -noinput test
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: target/doc
      - name: Commit to OBS
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
        run: |
          ant -lib /usr/share/java/ivy.jar -v -noinput obs.commit
